# Generated by Django 5.2.8 on 2025-11-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of successful logins. Used to enforce first-time password change.",
            ),
        ),
    ]
