# Generated by Django 5.2.8 on 2025-11-29 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_login_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useronboardingrequest",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User account created from this request, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="onboarding_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
